import { prisma } from "@/lib/prisma";
import { sendNotification } from "@/lib/notifications/sender";
import { NotificationType, TaskPriority } from "@prisma/client";

/**
 * Execute a workflow action based on type and config.
 * Called by the workflow engine when a rule's conditions match.
 */
export async function executeAction(
  type: string,
  config: Record<string, unknown>,
  entityData: Record<string, unknown>
) {
  switch (type) {
    case "create_task":
      await createTaskAction(config, entityData);
      break;
    case "send_email":
      await sendEmailAction(config, entityData);
      break;
    case "send_sms":
      await sendSmsAction(config, entityData);
      break;
    case "create_notification":
      await createNotificationAction(config, entityData);
      break;
    case "webhook":
      await webhookAction(config, entityData);
      break;
    default:
      console.warn(`Unknown workflow action type: ${type}`, config);
  }
}

/**
 * Create a task from workflow automation
 */
async function createTaskAction(
  config: Record<string, unknown>,
  entityData: Record<string, unknown>
) {
  const title = interpolate(config.title as string, entityData);
  const description = config.description
    ? interpolate(config.description as string, entityData)
    : null;

  // Determine assignee — config can specify a role or specific userId
  let assigneeId: string | null = null;
  if (config.assigneeId) {
    assigneeId = config.assigneeId as string;
  } else if (config.assigneeRole && entityData.organizationId) {
    // Find a user with the matching role in this org
    const user = await prisma.user.findFirst({
      where: {
        organizationId: entityData.organizationId as string,
        role: config.assigneeRole as any,
        isActive: true,
      },
    });
    assigneeId = user?.id || null;
  } else if (config.assigneeField && entityData[config.assigneeField as string]) {
    assigneeId = entityData[config.assigneeField as string] as string;
  }

  // Need a createdById — use the actor or fall back to assignee
  const createdById =
    (entityData.changedById as string) ||
    (entityData.userId as string) ||
    assigneeId;

  if (!createdById) {
    console.warn("Cannot create task without createdById", config);
    return;
  }

  const daysUntilDue = (config.dueDays as number) || 3;
  const dueDate = new Date();
  dueDate.setDate(dueDate.getDate() + daysUntilDue);

  const task = await prisma.task.create({
    data: {
      title,
      description,
      loanId: (entityData.loanId as string) || (entityData.id as string) || null,
      assigneeId,
      createdById,
      priority: (config.priority as TaskPriority) || "MEDIUM",
      dueDate,
      isAutoGenerated: true,
      triggerEvent: `${entityData.triggerEntity || "workflow"}.${entityData.triggerEvent || "auto"}`,
    },
  });

  // Notify the assignee about the auto-generated task
  if (assigneeId && assigneeId !== createdById) {
    await sendNotification({
      userId: assigneeId,
      type: "TASK_ASSIGNED",
      title: "New Task (Auto-Generated)",
      message: title,
      loanId: task.loanId || undefined,
      actionUrl: task.loanId ? `/loans/${task.loanId}` : "/tasks",
    });
  }
}

/**
 * Send an email notification via Resend (or log in dev)
 */
async function sendEmailAction(
  config: Record<string, unknown>,
  entityData: Record<string, unknown>
) {
  const to = config.to
    ? interpolate(config.to as string, entityData)
    : (entityData.borrowerEmail as string);
  const subject = interpolate((config.subject as string) || "StrongBox Notification", entityData);
  const body = interpolate((config.body as string) || "", entityData);

  if (!to) {
    console.warn("No email recipient for send_email action", config);
    return;
  }

  // In production, integrate with Resend or similar service
  if (process.env.RESEND_API_KEY) {
    try {
      await fetch("https://api.resend.com/emails", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${process.env.RESEND_API_KEY}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          from: process.env.EMAIL_FROM || "noreply@strongbox.app",
          to,
          subject,
          html: body,
        }),
      });
    } catch (err) {
      console.error("Failed to send email:", err);
    }
  } else {
    console.log(`[DEV] Email to ${to}: ${subject}`);
  }
}

/**
 * Send an SMS via Twilio (or log in dev)
 */
async function sendSmsAction(
  config: Record<string, unknown>,
  entityData: Record<string, unknown>
) {
  const to = config.to
    ? interpolate(config.to as string, entityData)
    : (entityData.borrowerPhone as string);
  const message = interpolate((config.message as string) || "", entityData);

  if (!to || !message) {
    console.warn("No SMS recipient or message for send_sms action", config);
    return;
  }

  if (process.env.TWILIO_ACCOUNT_SID && process.env.TWILIO_AUTH_TOKEN) {
    try {
      const authString = Buffer.from(
        `${process.env.TWILIO_ACCOUNT_SID}:${process.env.TWILIO_AUTH_TOKEN}`
      ).toString("base64");
      await fetch(
        `https://api.twilio.com/2010-04-01/Accounts/${process.env.TWILIO_ACCOUNT_SID}/Messages.json`,
        {
          method: "POST",
          headers: {
            Authorization: `Basic ${authString}`,
            "Content-Type": "application/x-www-form-urlencoded",
          },
          body: new URLSearchParams({
            To: to,
            From: process.env.TWILIO_PHONE_NUMBER || "",
            Body: message,
          }),
        }
      );
    } catch (err) {
      console.error("Failed to send SMS:", err);
    }
  } else {
    console.log(`[DEV] SMS to ${to}: ${message}`);
  }
}

/**
 * Create an in-app notification
 */
async function createNotificationAction(
  config: Record<string, unknown>,
  entityData: Record<string, unknown>
) {
  const userId =
    (config.userId as string) ||
    (config.userIdField ? (entityData[config.userIdField as string] as string) : null);

  if (!userId) {
    console.warn("No userId for create_notification action", config);
    return;
  }

  const title = interpolate((config.title as string) || "Notification", entityData);
  const message = interpolate((config.message as string) || "", entityData);

  await sendNotification({
    userId,
    type: (config.notificationType as NotificationType) || "SYSTEM",
    title,
    message,
    loanId: (entityData.loanId as string) || (entityData.id as string) || undefined,
    actionUrl: config.actionUrl
      ? interpolate(config.actionUrl as string, entityData)
      : undefined,
  });
}

/**
 * Fire a webhook to an external URL
 */
async function webhookAction(
  config: Record<string, unknown>,
  entityData: Record<string, unknown>
) {
  const url = config.url as string;
  if (!url) {
    console.warn("No URL for webhook action", config);
    return;
  }

  try {
    await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        ...(config.headers as Record<string, string> | undefined),
      },
      body: JSON.stringify({
        event: `${entityData.triggerEntity}.${entityData.triggerEvent}`,
        data: entityData,
        timestamp: new Date().toISOString(),
      }),
    });
  } catch (err) {
    console.error("Webhook failed:", err);
  }
}

/**
 * Simple template interpolation: replaces {{key}} with entityData[key]
 */
function interpolate(template: string, data: Record<string, unknown>): string {
  if (!template) return "";
  return template.replace(/\{\{(\w+)\}\}/g, (_, key) => {
    const val = data[key];
    return val !== undefined && val !== null ? String(val) : "";
  });
}
