import { NextRequest, NextResponse } from "next/server";
import { withAuth } from "@/lib/auth/api-guard";
import { prisma } from "@/lib/prisma";
import { writeAuditLog } from "@/lib/audit/logger";
import { sendNotification } from "@/lib/notifications/sender";
import {
  canTransition,
  checkTransitionGuards,
  getSideEffects,
  type LoanGuardData,
} from "@/lib/loans/stateMachine";
import { evaluateWorkflowRules } from "@/lib/workflow/engine";
import { generateIOSchedule } from "@/lib/payments/schedule";
import Decimal from "decimal.js";
import { LoanStatus, TaskPriority } from "@prisma/client";

export const POST = withAuth(async (request, ctx) => {
  const segments = request.nextUrl.pathname.split("/");
  const id = segments[segments.length - 2]; // /api/loans/[id]/status
  const body = await request.json();
  const { status: newStatus, reason, skipGuards } = body;

  if (!newStatus || !Object.values(LoanStatus).includes(newStatus)) {
    return NextResponse.json({ error: "Invalid status" }, { status: 400 });
  }

  const loan = await prisma.loan.findFirst({
    where: { id, organizationId: ctx.organizationId },
    include: {
      borrower: { select: { email: true, phone: true, firstName: true, lastName: true } },
    },
  });

  if (!loan) {
    return NextResponse.json({ error: "Loan not found" }, { status: 404 });
  }

  if (!canTransition(loan.status, newStatus as LoanStatus)) {
    return NextResponse.json(
      { error: `Cannot transition from ${loan.status} to ${newStatus}` },
      { status: 400 }
    );
  }

  // Check guard conditions (unless admin is force-skipping)
  if (!skipGuards) {
    const [requiredDocs, conditions] = await Promise.all([
      prisma.document.findMany({
        where: { loanId: id, isRequired: true },
        select: { isReceived: true },
      }),
      prisma.loanCondition.findMany({
        where: { loanId: id },
        select: { isCleared: true, category: true },
      }),
    ]);

    const guardData: LoanGuardData = {
      id: loan.id,
      borrowerId: loan.borrowerId,
      propertyId: loan.propertyId,
      loanOfficerId: loan.loanOfficerId,
      processorId: loan.processorId,
      underwriterId: loan.underwriterId,
      loanAmount: Number(loan.loanAmount),
      interestRate: Number(loan.interestRate),
      termMonths: loan.termMonths,
      riskScore: loan.riskScore,
      requiredDocsReceived:
        requiredDocs.length === 0 || requiredDocs.every((d) => d.isReceived),
      conditionsCleared: conditions.every((c) => c.isCleared),
      priorToApprovalCleared: conditions
        .filter((c) => c.category === "Prior-to-approval")
        .every((c) => c.isCleared),
      priorToFundingCleared: conditions
        .filter((c) => c.category === "Prior-to-funding")
        .every((c) => c.isCleared),
    };

    const guardFailures = checkTransitionGuards(
      loan.status,
      newStatus as LoanStatus,
      guardData
    );

    if (guardFailures.length > 0) {
      return NextResponse.json(
        { error: "Transition guard conditions not met", guardFailures },
        { status: 422 }
      );
    }
  }

  // Update loan status
  const now = new Date();
  const statusDateField = getStatusDateField(newStatus as LoanStatus);
  const updateData: Record<string, unknown> = {
    status: newStatus,
    previousStatus: loan.status,
  };
  if (statusDateField) {
    updateData[statusDateField] = now;
  }
  if (newStatus === "DENIED" && reason) {
    updateData.denialReason = reason;
  }

  const updated = await prisma.loan.update({
    where: { id },
    data: updateData as any,
  });

  // Record status history
  await prisma.loanStatusHistory.create({
    data: {
      loanId: id,
      fromStatus: loan.status,
      toStatus: newStatus as LoanStatus,
      changedById: ctx.user.id,
      reason,
    },
  });

  // Execute automated side effects (create tasks)
  const sideEffects = getSideEffects(newStatus as LoanStatus);
  if (sideEffects) {
    for (const taskDef of sideEffects.tasks) {
      const assigneeId = (loan as any)[taskDef.assigneeField] || ctx.user.id;
      const dueDate = new Date();
      dueDate.setDate(dueDate.getDate() + taskDef.dueDays);

      await prisma.task.create({
        data: {
          title: taskDef.title,
          loanId: id,
          assigneeId,
          createdById: ctx.user.id,
          priority: taskDef.priority as TaskPriority,
          dueDate,
          isAutoGenerated: true,
          triggerEvent: `status_change.${newStatus}`,
        },
      });

      if (assigneeId !== ctx.user.id) {
        await sendNotification({
          userId: assigneeId,
          type: "TASK_ASSIGNED",
          title: "New Task (Auto-Generated)",
          message: `${taskDef.title} — Loan ${loan.loanNumber}`,
          loanId: id,
          actionUrl: `/loans/${id}`,
        });
      }
    }
  }

  // Auto-generate payment schedule when loan is funded
  if (newStatus === "FUNDED") {
    try {
      const existingPayments = await prisma.payment.count({ where: { loanId: id } });
      if (existingPayments === 0) {
        const firstPaymentDate = loan.firstPaymentDate || new Date();
        const schedule = generateIOSchedule({
          loanAmount: new Decimal(loan.loanAmount.toString()),
          annualRate: new Decimal(loan.interestRate.toString()),
          termMonths: loan.termMonths,
          firstPaymentDate,
        });

        await prisma.$transaction(
          schedule.map((p) =>
            prisma.payment.create({
              data: {
                loanId: id,
                amount: p.amount.toNumber(),
                principalAmount: p.principalAmount.toNumber(),
                interestAmount: p.interestAmount.toNumber(),
                dueDate: p.dueDate,
                status: "SCHEDULED",
              },
            })
          )
        );

        await prisma.loan.update({
          where: { id },
          data: {
            firstPaymentDate,
            nextPaymentDue: firstPaymentDate,
            currentBalance: loan.loanAmount,
          },
        });
      }
    } catch (err) {
      console.error("Failed to auto-generate payment schedule:", err);
    }
  }

  // Notify loan officer of status change
  if (loan.loanOfficerId && loan.loanOfficerId !== ctx.user.id) {
    await sendNotification({
      userId: loan.loanOfficerId,
      type: "STATUS_CHANGE",
      title: "Loan Status Updated",
      message: `${loan.loanNumber} moved from ${loan.status} to ${newStatus}`,
      loanId: id,
      actionUrl: `/loans/${id}`,
    });
  }

  // Evaluate custom workflow rules
  try {
    await evaluateWorkflowRules({
      organizationId: ctx.organizationId,
      triggerEntity: "Loan",
      triggerEvent: "status_change",
      entityData: {
        ...updated,
        loanAmount: Number(updated.loanAmount),
        interestRate: Number(updated.interestRate),
        previousStatus: loan.status,
        changedById: ctx.user.id,
        borrowerEmail: loan.borrower?.email,
        borrowerPhone: loan.borrower?.phone,
        borrowerName: `${loan.borrower?.firstName} ${loan.borrower?.lastName}`,
      } as any,
    });
  } catch (err) {
    console.error("Workflow rule evaluation failed:", err);
  }

  await writeAuditLog({
    organizationId: ctx.organizationId,
    action: "STATUS_CHANGE",
    entityType: "Loan",
    entityId: id,
    description: `Changed loan ${loan.loanNumber} status from ${loan.status} to ${newStatus}`,
    userId: ctx.user.id,
    userEmail: ctx.user.email,
    before: { status: loan.status } as any,
    after: { status: newStatus } as any,
  });

  return NextResponse.json({ loan: updated });
}, "change_loan_status");

function getStatusDateField(status: LoanStatus): string | null {
  const map: Partial<Record<LoanStatus, string>> = {
    APPLICATION: "applicationDate",
    CONDITIONAL_APPROVAL: "conditionalApprovalDate",
    APPROVED: "approvalDate",
    CLOSING: "closingDate",
    FUNDED: "fundingDate",
    DENIED: "denialDate",
    PAYOFF_REQUESTED: "payoffDate",
    PAID_OFF: "payoffDate",
    DEFAULT: "defaultDate",
    EXTENDED: "extensionDate",
  };
  return map[status] || null;
}
